version: '3.0'
services:
  tasks_api:
    container_name: 'tasks_api'
    build:
      context: ./../../../..
      dockerfile: ./apps/tasks/build/docker/dev/Dockerfile
    volumes:
      - ./../../../tasks:/app/apps/tasks
      - ./../../../shared:/app/apps/shared
      - ./../../../notifications:/app/apps/notifications
    ports:
      - '3000:3000'
    depends_on:
      - tasks_database
    env_file:
      - .dev.tasks.env
    restart: 'always'

  tasks_database:
    container_name: 'tasks_database'
    image: 'mariadb:10.5.8'
    ports:
      - "3308:3306"
    volumes:
      - tasks_db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'tasks'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Jerusalem
    restart: 'always'

volumes:
  tasks_db_data: